# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
proxy:
  https:
    enabled: true
    hosts:
      - <jupyterhub-hostname>
    letsencrypt:
      contactEmail: <email>
hub:
  db:
    type: sqlite-memory
  config:
    CILogonOAuthenticator:
      client_id: <client-id>
      client_secret: <client-secret>
      oauth_callback_url: <jupyterhub-hostname>/hub/oauth_callback
      username_claim: email
    JupyterHub:
      authenticator_class: cilogon
singleuser:
  storage:
    capacity: 1Gi
    extraVolumes:
      - name: geoedf-config
        configMap:
          name: geoedf-config
    extraVolumeMounts:
      - name: geoedf-config
        mountPath: /home/jovyan/.config
  cmd: run.sh
  image:
    name: geoedf/standalone
    tag: v183
  profileList:
    - display_name: "GeoEDF v183"
      description: "GeoEDF Workflow Engine v1.83"
      default: true
    - display_name: "GeoEDF v182"
      description: "GeoEDF Workflow Engine v1.82 for debugging"
      kubespawner_override:
        image: geoedf/standalone:v182
  extraPodConfig:
    securityContext:
      allowPrivilegeEscalation: false
  extraAnnotations:
    container.apparmor.security.beta.kubernetes.io/notebook: unconfined
